### ISSUE TITLE
Command attributes are not replaced when force installing an altered bundle

### ISSUE THREAD

**Issue by vanstee** [operable/cog#1138] opened 2016-11-09 19:15 UTC
I've had trouble reproducing this, but if I only add options to a command and then force install it, I've seen those options not parsed correctly upon invocation. If this can't be repro'd feel free to close it.

**Comment by mpeck** [comment] 2016-11-15 21:44
I can't seem to reproduce this. I've tried adding and removing options and just editing already existing options. It seems to be working for me. I'm gonna close this for now, if it comes up again later we can revisit.

**Closed** 2016-11-15 21:44 UTC
Labels: research
