### ISSUE TITLE
Track chat users by internal ID, not (only) chat handle

### ISSUE THREAD

**Issue by christophermaier** [operable/cog#353] opened 2016-03-08 19:47 UTC
Chat platforms often give users a stable internal ID as well as a public "handle", which can change. When available, we should use the internal ID to resolve a Cog user instead of just the handle.

Without this, users that change their handle would need to make a corresponding change in Cog in order to continue using Cog. Additionally, another user could change their handle to the old handle of the first user and thus "inherit" their permissions.

**Comment by mpeck** [comment] 2016-03-09 16:39
Looks like this might be a duplicate of #305

**Comment by vanstee** [comment] 2016-03-15 18:28
Comment from @imbriaco in duplicate issue:

There was a good conversation in cogbot chat tonight (thanks @ptinsley!) regarding handles and the safety of using them as a primary identifier to map chat provider users to cog users. I think there is a big enough concern that we should consider moving from handles to provider-specific user IDs. In cases where there may not be a user ID (ahem, IRC) we will have to be creative and carefully document the tradeoffs we make.

The primary problem with handles is that they can be changed by users. In the case of HipChat, for example, it's particularly troublesome since two different users can have what appears to us via XMPP to be exactly the same handle as long as they're not in the same room at the same time.

I think we can keep using handles for provisioning users, we just look them up at handle create time and convert to permanent IDs. There's a short but acceptable race condition there.

**Comment by vanstee** [comment] 2016-03-15 18:37
Slack and HipChat both have ids we can use, so IRC will be a little more interesting.

Here's a pan for some tiny PRs to get this worked out:

* [ ] Add provider_user_id column (not null) to chat_handles table
* [ ] Include provider_user_id field when creating chat-handles via the api. The call will remain the same, but we'll ask the adapter for the provider_user_id before creating the record
* [ ] When looking up the rules for the user, force the call to be made with the id rather than the handle (for IRC the id will be the handle so those calls will still work).
* [ ] Ensure that HipChat id's are unique to HipChat and not just per room. If not, append room info to the provider_user_id.

**Comment by vanstee** [comment] 2016-03-18 18:53
PR: https://github.com/operable/cog/pull/426

**Closed** 2016-03-22 15:35 UTC
Labels: bug, cog, review
